# Tutorials on the PyTorch 
## Tensor methods and attributes

__Imports__

In [2]:
import torch
import numpy as np

__Initializing a Tensor__

In [3]:

data = [[1, 2], [3, 4]]


#convert any data directly into a tensor 
x_data = torch.tensor(data)


#or process it as a numpy array and then convert it into a tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


#convert a tensor from another tensor
#It uses the existing tensor as a template for its shape and technical properties,
#but it does not copy its values.
x_ones = torch.ones_like(x_data)  # retains the properties of x_data

#Now we can compare the attributes of x_ones and x_data
print(f"Data: {x_data} \n")
print(f"Ones Tensor: {x_ones} \n")

print(f"Shape of data tensor: {x_data.shape} \n")
print(f"Shape of ones tensor: {x_ones.shape} \n")

print(f"Datatype of data tensor: {x_data.dtype} \n")
print(f"Datatype of ones tensor: {x_ones.dtype} \n")


#Now we can also create a new tensor with the same shape as x_data,
#but it will be filled with random values and we can also override the datatype of x_data
x_rand = torch.rand_like(x_data, dtype = torch.float)  # overrides the datatype of x_data

print(f"Random Tensor: {x_rand} \n")


#And we can also create a new zero tensor with the same shape and datatype as x_data
x_zeros = torch.zeros_like(x_data)  # retains the properties of x_data
print(f"Zeros Tensor: {x_zeros} \n")


# Note that all of the above methods do not modify the original tensor, but rather create a new tensor with the specified properties.
#and all of the above methods also are ran on the CPU, which is the default device for PyTorch tensors. 
# If you want to run your tensor operations on a GPU, you can specify the device when creating the tensor, 
# like this: device="cuda" :
# In order to do this quicker we can set device variable in order to reuse it quickly:(
#but the common practice is to specify the device when creating the tensor, rather than moving it later. and it should be 
#done with if else statements to check if the GPU is available or not, like this:)
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

x = torch.ones((3, 3), device=device)  # creates a tensor on the GPU
print(f"Tensor on GPU: {x} \n")


#Note that if you want to move an existing tensor to a different device, you can use the .to() method:
x_cpu = x.to("cpu")  # moves the tensor to the CPU
print(f"Tensor moved to CPU: {x_cpu} \n")


x_gpu = x_cpu.to(device)  # moves the tensor back to the GPU
print(f"Tensor moved back to GPU: {x_gpu} \n")


#What wasn't mentioned before, is that we can genuinely create a tensor with a specific shape and datatype, without using any existing tensor as a template.
#We can do this by using the torch.empty(), torch.zeros(), torch.ones(), and torch.rand() functions, 
# which allow us to specify the shape and datatype of the tensor we want to create:
shape = (2,3)
rand_tensor = torch.rand(
    shape, 
    dtype = torch.float, 
    device = device
)
ones_tensor = torch.ones( 
    shape, 
    dtype = torch.float, 
    device = device
)

zeros_tensor = torch.zeros( 
    shape, 
    dtype = torch.float, 
    device = device
)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Data: tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: tensor([[1, 1],
        [1, 1]]) 

Shape of data tensor: torch.Size([2, 2]) 

Shape of ones tensor: torch.Size([2, 2]) 

Datatype of data tensor: torch.int64 

Datatype of ones tensor: torch.int64 

Random Tensor: tensor([[4.7142e-01, 1.7011e-04],
        [2.6808e-01, 3.3300e-01]]) 

Zeros Tensor: tensor([[0, 0],
        [0, 0]]) 

Tensor on GPU: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0') 

Tensor moved to CPU: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Tensor moved back to GPU: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0') 

Random Tensor: 
 tensor([[0.0716, 0.4663, 0.7559],
        [0.2568, 0.7449, 0.7176]], device='cuda:0') 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0') 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


__More details on Attributes of a Tensor__

In [4]:
print(f"Shape of tensor: {ones_tensor.shape}")
print(f"Datatype of tensor: {ones_tensor.dtype}")
print(f"Device tensor is stored on: {ones_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


__Operations on Tensors__

__Standard numpy-like indexing and slicing:__

In [5]:
tensor = torch.ones(4,4)

print(f" first row: \n {tensor[0]}")





#Outer producs are essentially a way you multiply tensors: (v⊗w=vw⊤.)



 first row: 
 tensor([1., 1., 1., 1.])


Outer producs are essentially a way you multiply tensors:
<br>
$v⊗w = vw^T$

In [6]:
v = torch.tensor([1.0, 2.0])
w = torch.tensor([3.0, 4.0, 5.0])

T = torch.outer(v, w)
print(f"Tensor v: \n {v} \n")
print(f"Tensor w: \n {w} \n")
print(f"Tensor product of v and w: \n {T} \n")

Tensor v: 
 tensor([1., 2.]) 

Tensor w: 
 tensor([3., 4., 5.]) 

Tensor product of v and w: 
 tensor([[ 3.,  4.,  5.],
        [ 6.,  8., 10.]]) 

